# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast prox for the Sorted L1 norm
#' 
#' A fast stack-based algorithm for the prox for the Sorted L1 norm.
#'
#' See Algorithm 4 in Bogdan et. al. (2015).
#'
#' @param y A vector whose entries should form a nonincreasing sequence.
#'   This parameter has to be of type (R internal storage mode) \code{double}.
#' @param lambda A vector whose entries should form a nonincreasing sequence
#'   This parameter has to be of type (R internal storage mode) \code{double}.
#'
#' @references M. Bogdan, E. van den Berg, C. Sabatti, W. Su, E. Candes (2015), \emph{SLOPE - Adaptive variable selection via convex optimization}, \url{http://arxiv.org/abs/1407.3824}
#'
#' @export
proxSortedL1Rcpp <- function(y, lambda) {
    .Call('grpSLOPE_proxSortedL1Rcpp', PACKAGE = 'grpSLOPE', y, lambda)
}

#' Test
#'
#' @export
rcpp_hello <- function() {
    .Call('grpSLOPE_rcpp_hello', PACKAGE = 'grpSLOPE')
}

