# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

proxSortedL1Rcpp <- function(y, lambda) {
    .Call('grpSLOPE_proxSortedL1Rcpp', PACKAGE = 'grpSLOPE', y, lambda)
}

#' Test
#'
#' @export
rcpp_hello <- function() {
    .Call('grpSLOPE_rcpp_hello', PACKAGE = 'grpSLOPE')
}

